[profile.default]
solc = "0.8.13"
optimizer_runs = 1000000
bytecode_hash = "none"
no_match_test = "FFI|LongRunning"

[profile.intense]
fuzz_runs = 10000
no_match_test = "FFI"

[profile.ffi]
ffi = true
no_match_test = "LongRunning"
